server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 自动从nacos发现服务
      routes:
        - id: mind-upload-service
          uri: lb://mind-upload-service
          predicates:
            - Path=/api/upload/**
          filters:
            - StripPrefix=0
        - id: mind-file-service
          uri: lb://mind-file-service
          predicates:
            - Path=/api/knowledge/**,/api/document/**
          filters:
            - StripPrefix=0
        - id: mind-user-service
          uri: lb://mind-user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
  main:
    web-application-type: reactive
# JWT配置
jwt:
  secret: "bWluZC1haS1qd3Qtc2VjcmV0LWtleS0yMDI1LXNwcmluZy1ib290LTMtc2VjdXJpdHktdG9rZW4tbWFuYWdlbWVudC1zeXN0ZW0tYWR2YW5jZWQtdmVyc2lvbg=="
  expiration: 1800000  # 30分钟，单位毫秒
  token-prefix: "Bearer "
  header: "Authorization"