spring:
  application:
    name: mind-search-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      # 没有密码，保持简洁
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mind_ai
    jdbc-url: jdbc:postgresql://localhost:5432/mind_ai
    username: mind_user
    password: mind123
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  rabbitmq:
    host: 127.0.0.1          # MQ 地址
    port: 5672              # 端口
    username: guest         # 默认用户名
    password: guest         # 默认密码
    virtual-host: /         # 默认虚拟主机
    listener:
      simple:
        retry:
          enabled: false
        acknowledge-mode: manual # 手动确认消息
    publisher-confirm-type: correlated #开启消息确认机制
    publisher-returns: true #开启消息退回机制
    template:
      mandatory: true

  elasticsearch:
    uris: http://localhost:19200
    restclient:
      ssl:
        verification: none
# MyBatis-Plus配置
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


# 应用配置
server:
  port: 8084
  servlet:
    context-path: /api
logging:
  level:
    com.yourname: debug
    org.springframework.web: info
